setup:
  name: fluid-aware-retinal-segmentation
  model:
    backbone: resnet101
    use_dilation: [False, False, True]
    tasks:
      layer_seg:
        head: padnet+
        kwargs:
          aspp_rates: [6, 12, 18]
          intermediate_aspp: True
          num_ch_dec: [64, 128, 128, 256, 256]
          num_out_ch: 6   # Number of retinal layers
          active_scales: [0, 1]
      fluid_seg:
        head: padnet+
        kwargs:
          aspp_rates: [6, 12, 18]
          intermediate_aspp: True
          num_ch_dec: [64, 128, 128, 256, 256]
          num_out_ch: 1   # Binary segmentation
          active_scales: [0, 1]
  kwargs:
    ablation: ['SxTAM', 'SA', 'add']  # Or adjust based on your experiments
    enc_layers: [[4, 3, 2, 1], [0]]
    stages: [1]

  loss:
    tasks:
      layer_seg:
        loss: fluid_layer_seg
        kwargs:
          n_classes: 6
          scales: [0, 1]
          weight: 1
      fluid_seg:
        loss: bce_logits
        kwargs:
          scales: [0, 1]
          weight: 1
    kwargs:
      baselines:
        layer_seg: 0.7     # can be Dice or mIoU as baseline
        fluid_seg: 0.9
      gammas:
        layer_seg: 1
        fluid_seg: 1

  lr:
    default: 1.0e-4
    backbone: 1.0e-5

optim:
  name: Adam
  kwargs:
    betas: [0.9, 0.98]
  clip_grad_norm: 10

scheduler:
  name: step
  kwargs:
    step_size: 30_000
    gamma: 0.1
